sqlite3 < extract_score_1.sql
sqlite3 < extract_score_2.sql
sqlite3 < extract_score_3.sql
sqlite3 < extract_score_4.sql
sqlite3 < extract_score_5.sql
sqlite3 < extract_score_6.sql
sqlite3 < extract_score_7.sql
sqlite3 < extract_score_8.sql
sqlite3 < extract_score_9.sql
sqlite3 < extract_score_10.sql
sqlite3 < extract_score_11.sql
sqlite3 < extract_score_12.sql
sqlite3 < extract_score_13.sql
sqlite3 < extract_score_14.sql
sqlite3 < extract_score_15.sql
sqlite3 < extract_score_16.sql
sqlite3 < extract_score_17.sql
sqlite3 < extract_score_18.sql
sqlite3 < extract_score_19.sql
sqlite3 < extract_score_20.sql
sqlite3 < extract_score_21.sql
sqlite3 < extract_score_22.sql
sqlite3 < extract_score_23.sql
sqlite3 < extract_score_24.sql
